BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Aspect] (
    [id] INT NOT NULL IDENTITY(1,1),
    [name] NVARCHAR(1000) NOT NULL,
    [description] NVARCHAR(1000) NOT NULL,
    [minValue] INT NOT NULL,
    [maxValue] INT NOT NULL,
    [weight] INT NOT NULL,
    CONSTRAINT [Aspect_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
