export enum PATHS {
  INDEX = '/',
  RESULTS = '/results',
  LOGIN = '/login',
  CRITERIA = '/admin/criteria',
  CATEGORIES = '/admin/categories',
  SEASONS = '/admin/seasons',
  USERS = '/admin/users',
  EVENTS = '/events',
  RATINGS = '/ratings',
  AUTHORIZED = '/authorized',
  PROFILE = '/profile',
  ADMIN = '/admin',
  ERROR = '/error',
  IMPRESSUM = '/impressum',
}
