import * as env from 'env-var'

export const DB_SERVER = env.get('DB_SERVER').default('localhost').asString()
export const DB_USER = env.get('DB_USER').default('function_user').asString()
export const DB_PWD = env.get('DB_PWD').default('könnyűJelszó53').asString()
export const DB_ADMIN_USER = env.get('DB_ADMIN_USER').default('sa').asString()
export const DB_ADMIN_PWD = env.get('DB_ADMIN_PWD').default('Pr1sm4_Pr1sm4').asString()
export const DB_NAME = env.get('DB_NAME').default('pontozo-db').asString()
export const ENCRYPT = env.get('ENCRYPT').default('false').asBool()
export const REDIS_HOST = env.get('REDIS_HOST').default('localhost').asString()
export const REDIS_PORT = env.get('REDIS_PORT').default(6379).asInt()
export const REDIS_PWD = env.get('REDIS_PWD').default('hablatyrandomszoveg1235t436').asString()
export const APIM_HOST = env.get('APIM_HOST').default('https://pontozoapim.azure-api.net').asString()
export const APIM_KEY = env.get('APIM_KEY').default('').asString()
export const CLIENT_ID = env.get('CLIENT_ID').default('').asString()
export const CLIENT_SECRET = env.get('CLIENT_SECRET').default('').asString()
export const JWT_SECRET = env.get('JWT_SECRET').default('secretttxd').asString()
export const FUNCTION_HOST = env.get('FUNCTION_HOST').default('http://localhost:3000').asString()
export const FRONTEND_URL = env.get('FRONTEND_URL').default('http://localhost:3001').asString()
export const ADMINS = env.get('ADMINS').default('[]').asJsonArray()
export const ENV = env.get('ENV').default('development').asString()
