export const API_HOST = process.env.REACT_APP_API_HOST || 'http://localhost:7071/api'
export const CLIENT_ID = process.env.REACT_APP_CLIENT_ID || ''
export const CLIENT_SECRET = process.env.REACT_APP_CLIENT_SECRET || ''
export const MTFSZ_TOKEN = process.env.REACT_APP_MTFSZ_TOKEN || 'https://api.mtfsz.hu/oauth/v2/token'
export const MTFSZ_API_BASE = process.env.REACT_APP_MTFSZ_API_BASE || 'https://api.mtfsz.hu/api/v1_0/'
