@startuml Pontoz-O Authentication Flow
hide footbox
skinparam sequenceMessageAlign center
participant user[
    =User
    ----
    """"
]

participant webapp[
    =Pontoz-O Client
    ----
    ""React Application""
]

participant mauth[
    =MTFSZ SSO
    ----
    ""OAuth Server""
]

participant mapi[
    =MTFSZ API
    ----
    ""Public REST API""
]

participant funcapp[
    =Pontoz-O Server
    ----
    ""Azure Functions App""
]

participant db[
    =Pontoz-O DB
    ----
    ""Azure SQL""
]

user -> webapp ++: 1: Click on Login button
webapp -> mauth ++: 2: Redirect to /auth
|||
mauth -> user ++: 3: Ask login credentials
|||
return 4: login credentials
|||
mauth -> user++: 5: Share user data with Pontoz-O?
|||
return 6: Yes
mauth -> funcapp --++: 7: Redirect to redirectURI with authorizationCode
|||
funcapp -> mauth++: 8: Call /token with authCode and secret
|||
return 9: token
funcapp -> mapi ++: 10: Get user data with token
|||
return 11: user data
funcapp -> db ++: 12: Get user roles
|||
return 13: user roles
|||
funcapp -> funcapp: 14: Create JWT with user data and roles
funcapp --> webapp--: 15: JWT
webapp -> webapp: 16: store JWT in cookie
return 17: User logged in!
@enduml
